=== xburgos/cassandra-maven-plugin/tags/chronos-1.0-beta-1/chronos-report-maven-plugin/src/main/java/org/codehaus/mojo/chronos/common/chronos-responsetimesamples.dtd
<!ELEMENT groupedresponsetimesamples (group | sample)*>
<!ATTLIST groupedresponsetimesamples
	succeeded CDATA "0"
>
<!ELEMENT group (responsetimesamplegroup)*>
<!ATTLIST group
	id CDATA "0"
>
<!ELEMENT responsetimesamplegroup EMPTY>
<!ATTLIST responsetimesamplegroup
	name CDATA ""
	index CDATA ""
>
<!ELEMENT sample EMPTY>
<!ATTLIST sample
	responsetime CDATA ""
	timestamp CDATA ""
	success CDATA ""
	threadId CDATA ""
>

=== xburgos/cassandra-maven-plugin/tags/chronos-1.0-beta-2/chronos-report-maven-plugin/src/test/resources/jmeter-nested-httpsample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE responsetimesamples PUBLIC "SYSTEM" "chronos-responsetimesamples.dtd">
<groupedresponsetimesamples succeeded="4">
    <responsetimesamplegroup name="/connect.jsp" index="92">
        <sample responsetime="2876" timestamp="1240337349466" success="true" threadId="JIRA Use Case 1-1"/>
    </responsetimesamplegroup>
    <responsetimesamplegroup name="/login.jsp" index="89">
        <sample responsetime="292" timestamp="1240337349466" success="true" threadId="JIRA Use Case 1-1"/>
    </responsetimesamplegroup>
    <responsetimesamplegroup name="/secure/" index="90">
        <sample responsetime="55" timestamp="1240337349767" success="true" threadId="JIRA Use Case 1-1"/>
    </responsetimesamplegroup>
    <responsetimesamplegroup name="/secure/Dashboard.jspa" index="91">
        <sample responsetime="2520" timestamp="1240337349822" success="true" threadId="JIRA Use Case 1-1"/>
    </responsetimesamplegroup>
</groupedresponsetimesamples>
